Repository idaholab/TMAP8, pull requests merged in 2024-12, with the labels that each got.

#226 Update contributing instructions to fetch upstream before reset
  doc/content/getting_started/contributing.md
Labels: documentation

#227 TMAP8 clean up V&V cases
  doc/content/examples/fuel_cycle/index.md
  doc/content/verification_and_validation/val-2a.md
  doc/content/verification_and_validation/val-2b.md
  doc/content/verification_and_validation/val-2c.md
  doc/content/verification_and_validation/ver-1a.md
  doc/content/verification_and_validation/ver-1b.md
  doc/content/verification_and_validation/ver-1c.md
  doc/content/verification_and_validation/ver-1d.md
  doc/content/verification_and_validation/ver-1dc.md
  doc/content/verification_and_validation/ver-1dd.md
  doc/content/verification_and_validation/ver-1e.md
  doc/content/verification_and_validation/ver-1fa.md
  doc/content/verification_and_validation/ver-1fb.md
  doc/content/verification_and_validation/ver-1g.md
  test/tests/val-2a/comparison_val-2a.py
  test/tests/val-2c/comparison_val-2c.py
  test/tests/ver-1a/comparison_ver-1a.py
  test/tests/ver-1b/comparison_ver-1b.py
  test/tests/ver-1c/comparison_ver-1c.py
  test/tests/ver-1d/comparison_ver-1d.py
  test/tests/ver-1dc/comparison_ver-1dc.py
  test/tests/ver-1dd/comparison_ver-1dd.py
  test/tests/ver-1e/comparison_ver-1e.py
  test/tests/ver-1fa/comparison_ver-1fa.py
  test/tests/ver-1fb/comparison_ver-1fb.py
Labels: documentation, V&V

#204 Add verification case val-2d
  doc/content/bib/tmap8.bib
  doc/content/verification_and_validation/figures/comparison_val-2d.py
  doc/content/verification_and_validation/figures/val-2d_schematic.png
  doc/content/verification_and_validation/index.md
  doc/content/verification_and_validation/val-2d.md
  test/tests/val-2d/comparison_val-2d.py
  test/tests/val-2d/gold/experiment_data_paper.csv
  test/tests/val-2d/gold/val-2d_limited_out.csv
  test/tests/val-2d/gold/val-2d_limited_out.e
  test/tests/val-2d/gold/val-2d_out.csv
  test/tests/val-2d/gold/val-2d_out.e
  test/tests/val-2d/tests
  test/tests/val-2d/val-2d.i
Labels: V&V
